# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "Answer" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"content" VARCHAR NOT NULL,"question" INTEGER NOT NULL);
create table "Question" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"quizz" INTEGER NOT NULL,"content" VARCHAR NOT NULL,"nextQuestion" INTEGER NOT NULL);
create table "Quizz" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"name" VARCHAR NOT NULL);
alter table "Answer" add constraint "QUESTION_ANSWER_FK" foreign key("question") references "Question"("id") on update NO ACTION on delete CASCADE;
alter table "Question" add constraint "QUIZZ_QUESTION_FK" foreign key("quizz") references "Quizz"("id") on update NO ACTION on delete CASCADE;

# --- !Downs

alter table "Answer" drop constraint "QUESTION_ANSWER_FK";
alter table "Question" drop constraint "QUIZZ_QUESTION_FK";
drop table "Answer";
drop table "Question";
drop table "Quizz";

